name: action-io-generator CI
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths:
      - 'action-io-generator/**'
      - '.github/workflows/ci-action-io-generator.yml'
  pull_request:
    paths:
      - 'action-io-generator/**'
      - '.github/workflows/ci-action-io-generator.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: action-io-generator

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint

  check-dist:
    name: Check Distribution
    runs-on: ubuntu-24.04
    env:
      BUNDLE_FILE: "dist/bin.js"
      BUNDLE_COMMAND: "npm run bundle"
      WORKDIR: "./action-io-generator"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install
        working-directory: ${{ env.WORKDIR }}
        run: npm ci

      - name: Verify Latest Bundle
        uses: ./bundle-verifier
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}
          working_directory: ${{ env.WORKDIR }}

  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: npm ci
      - run: npm run compile
      - run: npm test